[meta title:"GetWasted" description:"A mobile application designed to help you live conservatively and consciously" /]


[Header
  title:"Get Wasted"
  subtitle:"Us humans can breathe... the Earth should be able to too."/]


[Waypoint]
## Who We Are, What We Do
At the core of who we are, we aim to strengthen the zero waste community by providing a means of self-expression and 
personal growth for all.

GetWasted is a mobile tool designed to help individuals reduce the amount of waste they generate on a daily basis. 
This application leverages existing resources from established zero-wasters to provide rich, high quality information 
for the user. In addition to being a resource provider, GetWasted allows for its users to connect and challenge each-other. 
In much the same way Fitbit users challenge each-other to burn more calories and get moving, GetWasted allows its users to 
make friendly bets about who can reduce their waste output. Overall, GetWasted provides a one-stop solution to the average 
environmentally aware citizens hoping into reduce their overall waste-footprint.
[/Waypoint]

[Waypoint]
## What We Do
### Reduce
People have trouble forming
habits. Tracking progress and
setting goals will aid reducers
in making the impact they
dream of, which is why we 
created our **REDUCE** page.
[/Waypoint]

[Waypoint]
### Share
Since going zero waste is a lifestyle 
change, getting help from the friends
and community members will be a vital
part of the process. This is why we have
integrated a social aspect into our app
called **SHARE**.
[/Waypoint]

[Waypoint]
### Read
Living a zero waste lifestyle requires having
an understanding of how to live. So, we provided 
our users with a large collection of 
blog posts and articles pertaining to zero waste
and living zero waste with our **READ** page. 
[/Waypoint]

[Waypoint]
### Shop
The adaptation of this lifestyle is hard
if you don't have the necessary tools. So 
we provided our users with a searchable 
database of products and ideas that they
can buy from zero waste shops on our 
**SHOP** page.
[/Waypoint]